version: 2

jobs:
    test:
        docker:
            - image: circleci/node:8.9
        working_directory: ~/repo/frip-ui-react
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: yarn install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn test

    build_and_deploy:
        docker:
            - image: circleci/node:8.9
        working_directory: ~/repo/frip-ui-react
        steps:
            - checkout
            - run:
                name: Install dependencies
                working_directory: /
                command: |
                    sudo apt-get update
                    sudo apt-get install -y python-pip python-dev
                    sudo pip install awscli
                    aws --version
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: yarn install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn build-storybook
            - run: yarn deploy-storybook

workflows:
    version: 2
    test_and_deploy:
        jobs:
            - test
            - build_and_deploy:
                requires:
                    - test
                filters:
                    branches:
                        only: master
